### ISSUE TITLE
CNI cosmetics

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/release#113]
# Paths

We've had to put CNI bits in `/opt`, as there was no way to tell kubelet to look in other places. As of kubernetes/kubernetes#32151 (already in 1.4), we can pass `--cni-bin-dir=` as well as `--cni-conf-dir=` to kubelet. I makes sense to put the plugins into `/usr/lib/cni` or `/usr/lib/kubelet/cni/bin` or `/usr/libexec/cni` - anything other then `/opt` is good. The reason for this is that traditionally `/opt` is used for installing ad-hoc pieces, not for things installed by the package manager. We could also move `/etc/cni` to `/etc/kubernets/cni`, so we have everything in one directory.
# Package name

I seems like `kuberentes-cni` would be something user has to lookup, calling it `kubernetes-cni-basic-network-plugins` (or just `kubernetes-basic-network-plugins`) would make it more obvious. Word "basic" (or "vanilla" or "generic" or something similar) is also good, so we don't give user the impression that they'll have all the plugins.

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle 

I think `/etc/cni/bin` or just `/opt/cni/bin` (as it is now) are my preferred locations, as they have to work on CoreOS as well (where `/usr/` is `ro`)

About naming, `kubernetes-basic-cni` sgtm, if we think we have to change it

**Comment by mattymo** [comment]
I think `cni` should definitely be in the package name, with the (searchable) package description being `Kubernetes container network interface standard plugins`. Deciding over calling the plugins basic, standard, or so on is not too important to me.

Secondly, it would be nice to make a search tree (overrideable by --cni-bin-dir) to meet these requirements. No decent RPM/DEB packager wants to use /opt these days. /usr/lib/$PKGNAME/cni/ or /usr/libexec/$PKGNAME are both okay paths for me. /etc/cni/bin I would -1 because there should be nothing except configuration files in /etc.

**Comment by dims** [comment]
@errordeveloper @mattymo is this still relevant issue? can we please close the issue otherwise?

**Comment by errordeveloper** [comment]
I think it relevant.

**Comment by justaugustus** [comment]
/help
/milestone v1.15
/priority important-soon
/area release-eng
related: https://github.com/kubernetes/sig-release/issues/245

**Comment by justaugustus** [comment]
Closing as I agree with @BenTheElder's [assessment](https://github.com/kubernetes/release/issues/862#issuecomment-525408804) in https://github.com/kubernetes/release/issues/862.

We're planning on moving the CNI plugins into the kubelet package.
See here to track the deprecation of `kubernetes-cni` deb/rpm packages: https://github.com/kubernetes/release/issues/885

/close
