### ISSUE TITLE
[krel] Add krel anago subcommand to retrieve the build candidate

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1536]
Target of the implementation is to replace this piece of bash in anago with a new `krel anago` subcommand:
https://github.com/kubernetes/release/blob/8b9e5c8483acfc5aec67bece8d0114295d96562a/anago#L1141-L1222

This includes all called functions as well, like this fastforward check:
https://github.com/kubernetes/release/blob/8b9e5c8483acfc5aec67bece8d0114295d96562a/anago#L1103-L1139

As for all other krel issues, if anyone of the @kubernetes/release-managers is interested in taking this then feel free to drop you `/assign`. I can guide you through the details.

**Comment by tpepper** [comment]
@saschagrunert @justaugustus we should discuss this a little more.  We're at a choice point.  Do we go the direction of shifting anago under krel in a 'krel anago' way, or make krel replace the primary control flow (utterly fragile the point of being broken by design despite being the most beautifully complex stateful reentrant bash function call graph I've ever seen) with a simpler, iterative, deterministic one in go in krel (eg: `krel stage`, `krel release`).  I'd like us to consider beginning that move sooner than later on a feature branch.

**Comment by saschagrunert** [comment]
Thanks for taking this @rajibmitra! :pray: 
/help cancel

**Comment by saschagrunert** [comment]
This is now covered by https://github.com/kubernetes/release/issues/1673
