### ISSUE TITLE
kube-dns clusterip 

### ISSUE THREAD

**Issue by jicki** [kubernetes/release#188]
[root@k8s-master ~]#kubectl get svc --namespace=kube-system
NAME                   CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
kube-dns               **10.0.0.10**      <none>        53/UDP,53/TCP   2d

[root@k8s-master ~]#cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf  
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=**--cluster-dns=10.12.0.10** --cluster-domain=cluster.local"
Environment="KUBELET_EXTRA_ARGS=--v=4"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_EXTRA_ARGS

**Comment by colemickens** [comment]
What is the question?

**Comment by colemickens** [comment]
What is the question? (edit: sorry, just saw it finally -- the cluster ip in the kubeadm conf differs from the actual service clusterip in the cluster.)

**Comment by autostatic** [comment]
I had the same issue. After updating the kubelet package from the Google Kuberntes repo from 1.4.3 to 1.4.4 on Ubuntu 16.04 new pods could not resolve anything. Turned out that someone or something decided to change the cluster-dns IP in `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` from 100.64.0.10 to 10.96.0.10. After changing this back and restarting the Kubelet services everything worked again.
