### ISSUE TITLE
push-build.sh should have a `--release-suffix` flag.

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/release#203]
It'd be nice to be able to easily push a developer build to the `/ci/` directory somewhere that I am confident won't get in the way of jenkins. Something like `/ci/v1.6.0-alpha.0.123+abc123-cjcullen`. Bonus points if that also spit out some helper commands for creating/updating clusters at that version.

**Comment by ixdy** [comment]
I'd rather we create a separate directory than `/ci/` for developer builds. IMO `/ci/` should be used only for output from our CI build systems, as its name implies...

**Comment by jbeda** [comment]
It should be possible to override all paths for custom buckets so that these tools are useful for folks that are not Googlers.

**Comment by fejta** [comment]
Hasn't this been fixed? The `--stage=gs://foo/ci/whatever` flag will send this suffix var to `push-build.sh`
/assign @ixdy

**Comment by ixdy** [comment]
I think this a slightly different request - `--gcs-suffix` adds a suffix to `/ci`, not to the version string. For example, we use `-cross` so that cross-builds upload to `/ci-cross/vFoo`, and we use `/${JOB_NAME}` all over to upload PR artifacts into `/ci/${JOB_NAME}`.

I think GKE expects artifacts in `/ci/vFoo-blah/` so `--gcs-suffix` doesn't really help.

**Comment by ixdy** [comment]
@jbeda push-build.sh already has a `--bucket` flag.

**Comment by fejta** [comment]
In that case want to support this by teaching people to use `/ci/cjcullen/v1.6.0-alpha.0.123+abc123` and not support increase complexity in the space of possible version names.

**Comment by ixdy** [comment]
I think #286 fixed this by adding `--version-suffix`.
