### ISSUE TITLE
`krel release-notes --create-draft-pr` create the PR without asking

### ISSUE THREAD

**Issue by cici37** [kubernetes/release#2075]
#### What happened:
Trying to run command `krel release-notes --create-draft-pr --fork=cici37` to create release notes draft PR.
The PR is created without providing option to manually create pr later and skipped the option of editing the release notes as well.
Ref: the [PR](https://github.com/kubernetes/sig-release/pull/1578) created accidentally.

#### What you expected to happen:
When it reaches to the point of creating the PR, an option should be provided to skip raise the PR or manually raise the PR. It should also provide the option to edit the release notes.

#### How to reproduce it (as minimally and precisely as possible):
Install krel and try with command `krel release-notes --create-draft-pr --fork=yourfork`

#### Anything else we need to know?:
When I met this issue, I am at the time that the previous release notes pr has been raised/merged, and the next release tag hasn't been created.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by cici37** [comment]
cc @pmmalinov01 
Pavel mentioned he also met with the same issue before.

**Comment by Damans227** [comment]
Good catch @cici37

**Comment by cici37** [comment]
After a little bit of digging, this behavior is triggered by flag `autoCreatePullRequest`:
```
https://github.com/kubernetes/release/blob/master/cmd/krel/cmd/release_notes.go#L356
```

This flag was introduced together with the edit flow of `--fix` in this PR: https://github.com/kubernetes/release/pull/1467

Which will cause `krel release-notes --create-draft-pr` exit from interactive mode:
Ref: https://github.com/kubernetes/release/blob/d01242d7df4189c666b8f5517ccbb9d75c391d59/cmd/krel/cmd/release_notes.go#L465

I am not sure if it is an expected behavior. Please feel free to comment. Thank you

**Comment by puerco** [comment]
Hey @cici37 yes, this was done like this not because it was the best flow but it was only the first iteration of that flow and we have not done a lot of improvements yet. In later tools I've added confirmation at every step because I went through the same feeling you are all experiencing :upside_down_face:  Check here in `krel promote-images` for example:

https://github.com/kubernetes/release/blob/d01242d7df4189c666b8f5517ccbb9d75c391d59/cmd/krel/cmd/promote-images.go#L263-L274

So we can add that behavior, no problem. If you want to give it a go let me know and I can guide you if you need help.

Thanks for reporting !

**Comment by cici37** [comment]
@puerco Thank you for sharing the information. I would like to contribute for sure. Let me try to raise the pr and that will be great if you could help with reviewing :)

**Comment by puerco** [comment]
Of course, let me know if you have any questions :)
