### ISSUE TITLE
Upgrading kubeadm restarts kubelet

### ISSUE THREAD

**Issue by mnaser** [kubernetes/release#2412]
#### What happened:
When upgrading a Kubernetes cluster, one of the first steps is updating `kubeadm` to be the new version.   However, this causes an unnecessary restart to `kubelet`.

#### What you expected to happen:
The `kubelet` service should not be restarted, as it is expected to be restarted when the actual `kubelet` package is restarted.

#### How to reproduce it (as minimally and precisely as possible):
1. Have an existing cluster
2. `apt-get install kubeadm` (of newer version)
3. `kubelet` is restarted,

#### Anything else we need to know?:

https://github.com/kubernetes/release/blob/master/packages/deb/bionic/kubeadm/debian/postinst#L26

This part seems to restart the `kubelet` service if it's running, which I'm not sure why it's doing.  The `daemon-reload` should be enough to do and the `kubelet` restart should happen when `kubelet` is updated post-kubelet update if this is an upgrade.

#### Environment:

- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Comment by neolit123** [comment]
Kubeadm restarts the kubelet for new nodes or on upgrade so this can be
removed, IMO. I don't know when it was added.

**Comment by mnaser** [comment]
This is been a bit of a pain point for us, does it make sense to make a PR that drops that restart?

**Comment by neolit123** [comment]
makes sense to me, but such a PR needs to also fix the RPM packages if this problem is also present there..

we should remove this whole section:
https://github.com/kubernetes/release/blob/master/packages/deb/bionic/kubeadm/debian/postinst#L22-L27
a kubeadm package upgrade should not perform kubelet service actions, until the kubelet package is upgraded.

later in the upgrade process the user can reload / restart manually, as in:
> Restart the kubelet:
> ...

here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
also as noted in the past, we should probably fix these kubeadm deps eventually:
https://github.com/kubernetes/release/blob/d41c86508aac7f0b6d5f701fb2f6d3ae29bf35e0/cmd/kubepkg/templates/latest/deb/kubeadm/debian/control#L13

this would avoid the package holds in the docs.

in my view kubectl, kubeadm, kubelet should not depend on each other.
the k8s-CNI package is a kubelet requirement, while the CRI-tools package is one for kubeadm.

AFAIK, similar changes are not so easy to to do today, because they will affect PATCH releases in old MINOR releases of the packages.

**Comment by neolit123** [comment]
BTW, i think these are the up-to-date package spec locations:
https://github.com/kubernetes/release/blob/master/cmd/kubepkg/templates/latest

**Comment by mnaser** [comment]
I got around pushing a patch for this...

**Comment by neolit123** [comment]
/reopen

looks like https://github.com/kubernetes/release/pull/2496 is still open
