### ISSUE TITLE
K8s packages should be hosted on community infra

### ISSUE THREAD

**Issue by jbeda** [kubernetes/release#281]
It is clear the apt repository for the k8s packages are shared with other google repositories.

```
curl -iL https://apt.kubernetes.io/
```
```
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.10.3
Date: Sun, 12 Mar 2017 22:34:01 GMT
Content-Type: text/html
Content-Length: 161
Connection: keep-alive
Location: https://packages.cloud.google.com/apt/

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 302
Content-Type: text/html; charset=utf-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Date: Sun, 12 Mar 2017 22:34:01 GMT


<html>
  <head>
    <title>Directory listing for /apt//</title>
    <base href="/apt//">
  </head>
  <body>
    <h2>Index of /apt//</h2>
    <p></p>
    <a href="dists">dists</a><br />
    <a href="doc">doc</a><br />
    <a href="pool">pool</a><br />
    <a href="src">src</a><br />
  </body>
</html>
```

**Comment by luxas** [comment]
I totally agree @jbeda! We just took the fast route initially with @mikedanese publishing the debs on Google infra

I guess this transition will take some time as it will be a breaking change for consumers.
But we should probably spin up a community (CNCF) hosted infra for both binaries and packages, and gradually move to it during 2017 or so.

Other thoughts @ixdy @timstclair @dankohn @bgrant0607 @thockin?

**Comment by thockin** [comment]
No disagreement.  We need (at least):

* a budget
* a way to get CNCF to pay for infra
* a process for who gets to access/sysadmin this stuff

And maybe:

* hire a sysadmin or 2


For now, Google is paying for it.

**Comment by luxas** [comment]
Yup, I know, somebody's gotta pay :)
And it shouldn't go unsaid that I'm really happy Google is paying for it and maintaining it now, making it actually possible for us to publish binaries easily and quickly, but long-term this belongs to the independent foundation.

That's why I pinged Dan on this, I think he has insight into what CNCF can do here.
Also related is the shift from gcr.io/google_containers to something Kubernetes-wide that's maintained by the CNCF: https://github.com/kubernetes/release/issues/270

**Comment by thockin** [comment]
The gcr and gcs changeovers will be interesting to figure out, but luckily
we have a channel to those teams :)

**Comment by dankohn** [comment]
Just to confirm that CNCF is willing to take on the budget responsibility for this. Our preference would be to have companies that are contributing to Kubernetes continue to fulfill the sysadmin responsibilities, but once it is off Google infrastructure, non-Google sysadmins would be welcome.

Our strong preference would also be for someone from the Kubernetes community to take the lead scoping our requirements, including a budget and transition plan.

**Comment by thockin** [comment]
Dan, eventually we will have to have a conversation about sysadmins for the
rest of the kube infrastructure - from the website, to the test infra, to
the myriad little things we run to serve the community.  I am a poor
sysadmin at best. :)

**Comment by bgrant0607** [comment]
Like https://github.com/kubernetes/k8s.io, prow, mungegithub, ...

**Comment by gtaylor** [comment]
I saw some things mentioned about what needs to be done, but they aren't super concrete for me. Does anyone feel comfortable outlining the first few steps in starting this process? Links to examples of related docs that might show how things are done would be especially useful.

**Comment by thockin** [comment]
We are looking at making a new GCP "organization" for kubernetes stuff to
be hosted.  CNCF will pick up th ebillm but we have to run it (as it should
be).

**Comment by gtaylor** [comment]
Sounds reasonable. I'm around if help is needed!

**Comment by bgrant0607** [comment]
Note that kubernetes-charts and kubernetes-helm are GCP projects to which non-Googlers have access. Maybe we should set up more such projects for relatively independent subprojects.

**Comment by x13n** [comment]
What about images that are actually google-specific (e.g. [Stackdriver integration ones](https://github.com/GoogleCloudPlatform/k8s-stackdriver)), should they also use the new domain? Right now all manifests using them are referring to k8s.gcr.io.

**Comment by justaugustus** [comment]
Sascha, here's the tracking issue I was referring to in the last Releng meeting.
/unassign @timothysc 
/assign @saschagrunert

**Comment by spiffxp** [comment]
/wg k8s-infra
@dims @cblecker my memory on discussion of a community-hosted apt.kubernetes.io is lost to the sands of time, do either of you remember what is holding this back?

**Comment by dims** [comment]
@spiffxp a prereq as being able to sign the artifacts which we don't have a good path for yet

**Comment by justaugustus** [comment]
/milestone v1.22
/unassign @tpepper 
/priority important-longterm

Part of https://github.com/kubernetes/sig-release/issues/1372.

**Comment by BenTheElder** [comment]
Super late reply but:

> What about images that are actually google-specific (e.g. Stackdriver integration ones), should they also use the new domain? Right now all manifests using them are referring to k8s.gcr.io.

We host lots of stuff in the project that involve integration with specific vendor platforms, so I think that's fine.
Managed offerings like GKE should ideally consume images from their own hosting (I believe this is the case there now) though for various reasons, IMHO ...

----

For the record: While this issue is about the k8s packages, the conversation here veered off into the infra in general. The wg-k8s-infra effort and SIG Testing, SIG release, etc. have moved many things to community _controlled_ (though much of it google funded and GCP based), infrastructure.

This however is not one of them yet. Unlike GCR this is not a product offering we can "just" pull off migrating to a community controlled but google funded instance of. The package host is ~internal infrastructure meant for hosting official stuff like the gcloud SDK. We'll need to use something else entirely to move it to community control.

This should probably be pretty easy if someone wants to staff it, though the big question is likely that of signing packages, as currently googlers sign them via google's registry ...

Realistically we could probably just do something like docker etc., and create a key for the project and ask people to trust it / import it 🤷‍♂️

**Comment by justaugustus** [comment]
(@BenTheElder -- working on a plan for this in 1.21)

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/issues/100348#issuecomment-801415789

**Comment by justaugustus** [comment]
Closing this in favor of https://github.com/kubernetes/release/issues/913.
/close
