### ISSUE TITLE
CI builds are breaking after we stopped immediately building rc.0

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2972]
Immediately after cutting the March patch releases, the ci builds started failing:

![image](https://user-images.githubusercontent.com/3935899/226077518-7764a512-b4b1-4be3-b51c-9ce0d305c98f.png)

The error as shown in [the build log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-1-25/1636866946441940992/build-log.txt) shows its related to the version string:

```
level=info msg="Using build version: v1.25.8-1+3a14fe1af239a0"
level=fatal msg="failed to run: find latest version: build version v1.25.8-1+3a14fe1af239a0 is not valid for release"
```

Upon further investigation, the builds are failing because [the regular expressions that check the version](https://github.com/kubernetes/release/blob/834e5b98353b6c86b53c2b6acc442900a44790d3/pkg/release/release.go#L61C2-L62) string don't catch the gitCommt string without the `rc.0`:

   :point_right: This is matched: `v1.25.8-rc.0.31+36b707f892c523`
   :point_right: This is not matched: `v1.25.8-1+3a14fe1af239a0`

We only started seeing this as these are the first releases we cut after [we stopped building the rc.0 immediately after tagging the repo](https://github.com/kubernetes/release/pull/2765).

More details on [this slack thread in #release-ci-signal](https://kubernetes.slack.com/archives/CN0K3TE2C/p1679100698188689).

Thanks to @BenTheElder for reporting.

/cc @saschagrunert @kubernetes/release-engineering

**Comment by BenTheElder** [comment]
We could change the regex, but I think it's not expected that version string format would change. 
We have other code that parses and reacts to version strings, so for now without digging too deep into that I recommend that we add an rc.0 tag (but just the tag, no release).

**Comment by saschagrunert** [comment]
> We could change the regex, but I think it's not expected that version string format would change. 

It's not the format which changes, it's just a case which we have not considered yet. I think we should fix the regex, because it looks like that is matches now incorrectly group 4 of the `versionReleaseRE`:

https://github.com/kubernetes/release/blob/cbd865f7f88c16cb628fd7175faec9931cc714b0/pkg/release/release.go#L61

![screenshot](https://user-images.githubusercontent.com/695473/226288271-63f711a1-5809-41e3-a027-07a646a0d80b.png)

The last matching group (group 4) is wrongly matched in the regex, because it should be part of the `versionBuildRE`:

https://github.com/kubernetes/release/blob/cbd865f7f88c16cb628fd7175faec9931cc714b0/pkg/release/release.go#L62

![screenshot](https://user-images.githubusercontent.com/695473/226288591-bb4b0a30-4605-4370-80ca-8cde40978cff.png)

The assembling of the regular expressions make them fail, because in case of `v1.25.8-1+3a14fe1af239a0` it's now invalid:

https://github.com/kubernetes/release/blob/cbd865f7f88c16cb628fd7175faec9931cc714b0/pkg/release/release.go#L244

**Comment by xmudrii** [comment]
I'm +1 for changing the regex, it seems wrong.

I see two options here:

- We reintroduce the rc.0 tag, but without building artifacts
  - This is IMO not ideal because we almost always have artifacts for pushed tags. Not having artifacts might break someone or some use cases and then we have an issue again
  - I expect that in the future we'll have questions why we do it this way instead of completely dropping the tag and fixing the issue
- We fix the regex to match the new case
  - This feels like a proper and more sustainable fix to me, but I'm not sure if this is going to break some consumers/users. In general, I _think_ it should be safe, but we can never know for sure

**Comment by saschagrunert** [comment]
I agree having a tag without artifacts seems not correct.

**Comment by liggitt** [comment]
is this also blocking presubmit e2e runs on release branches? seeing 

> W0320 12:43:01.804] 2023/03/20 12:43:01 main.go:328: Something went wrong: failed to acquire k8s binaries: U=file:///go/src/k8s.io/kubernetes/_output/gcs-stage R=v1.26.3-3+df96302de9bd79 get-kube.sh failed: error during /workspace/get-kube.sh: exit status 1

in presubmits as well

**Comment by saschagrunert** [comment]
@xmudrii are you planning to work on this or should I take a stab on the regex?

**Comment by xmudrii** [comment]
@saschagrunert Can you please take care of it? I need to take care of jobs generation ahead of today's rc.0.

**Comment by liggitt** [comment]
actually, I think the fix is needed in https://github.com/kubernetes/kubernetes/blob/master/cluster/get-kube.sh/#L75 on all release branches :-/

**Comment by saschagrunert** [comment]
@liggitt proposed the regex changes in https://github.com/kubernetes/kubernetes/pull/116807

Another grep through k/k gave me no further results.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/116809#issuecomment-1477815155 is ready for review and picked cleanly to all release branches, CI is running now. I made very incremental changes commit by commit so it is easier to review

**Comment by liggitt** [comment]
we either need to reopen this or create a new issue, because blocking presubmits are still failing on all release branches

**Comment by liggitt** [comment]
KUBE_CI_VERSION_REGEX in kube-up needs updating, https://github.com/kubernetes/kubernetes/pull/116809 is open to do that, but the script used in presubmits is apparently not the one in the PR... see https://github.com/kubernetes/kubernetes/pull/116808#issuecomment-1478028979

**Comment by saschagrunert** [comment]
Reopening until we fixed the issues.

**Comment by liggitt** [comment]
https://github.com/kubernetes/test-infra/pull/29102 open to trigger kubekins build to pick up https://github.com/kubernetes/kubernetes/pull/116809

**Comment by liggitt** [comment]
kubekins images rebuilt, https://github.com/kubernetes/test-infra/pull/28975 open to update CI jobs to use them

**Comment by liggitt** [comment]
for completeness, should probably merge the picks of the kube-up regex change (https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+116809+-base%3Amaster), but AFAICT the presubmit breakages are resolved at this point

**Comment by saschagrunert** [comment]
Alright, closing this one now.

**Comment by cici37** [comment]
A issue was reported which is related: https://github.com/kubernetes/kubernetes/issues/117115
