### ISSUE TITLE
anago fails checking cloud account/auth

### ISSUE THREAD

**Issue by dclaar** [kubernetes/release#346]
Anago checks for authorization twice, one of which depends on parsing the output of `gcloud auth list`, which appears to have changed. With the gcloud version noted below, the command returns:
```shell
$ gcloud auth list
        Credentialed Accounts
ACTIVE  ACCOUNT
        foo@bar.com
*       some.user@gmail.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`

$
```
Which no longer matches the "- name" test (there's no dash).

One option is to use:
```shell
$ gcloud auth list --format="value(account)"
foo@bar.com
some.user@gmail.com
```
Which only shows the user names.

Another option would be to drop the first part altogether, since the second part essentially repeats the test, making the first redundant.

Affected code:
```shell
  gcloud_auth_list=$($GCLOUD auth list 2>/dev/null)
  for user in $G_AUTH_USER $userat; do
    logecho -n "Checking cloud account/auth $user: "
    if [[ "$gcloud_auth_list" =~ -\ $user ]] && \
       (logrun gcloud config set account $user && \
        logrun gcloud docker -- version >/dev/null 2>&1); then
      logecho -r "$OK"
```
gcloud version
```shell
$ gcloud --version
Google Cloud SDK 159.0.0
alpha 2017.03.24
beta 2017.03.24
bq 2.0.24
core 2017.06.09
gcloud 
gsutil 4.26
```

**Comment by dclaar** [comment]
The following code, which checks the active user, could use:
--filter=status:ACTIVE

**Comment by david-mcmahon** [comment]
Yep, I just updated my gcloud and they changed the output format, so
attempting to use their --format seems like a good plan.
The trouble is the auth list is used in two ways. 1) to determine what
accounts are auth'd and 2) ensuring an ACTIVE one.  Now I remember that's
why I didn't use --format because I needed the whole picture.
Go ahead and play with it to see how we can get that whole picture using
--format or some combination of options to gcloud to determine those two
conditions are met.
