### ISSUE TITLE
No worldwide location for legacy packages

### ISSUE THREAD

**Issue by blixco** [kubernetes/release#3512]
**This is a Feature Request**

**What would you like to be added**

Legacy versions of Kubernetes rpms / apt packages, back to 1.10.x

**Why is this needed**

A handful of programs I'm working with have a hard requirement to continue to support older versions of Kubernetes until their refresh cycle at the end of this year. Google no longer hosts the rpms / packages for any version, and it appears that the current yum repos only host newer than 1.24

The only mirrors that I can locate for the packages I currently require (1.15.12 being the "newest") are hosted on servers that are on every blacklist we use for safe packages; I can't even verify that they host the packages due to the restrictions we have in place.

**Comments**

Our installations are primarily entirely offline / disconnected, but we're in a crunch with this particular version as our disconnected SAN died, and we foolishly believed that the packages would not disappear from the internet.

**Comment by xmudrii** [comment]
As an open source project, we cannot support every release of Kubernetes. This is a bit unfortunate, but backfilling repositories with old versions and hosting those old versions require a lot of time and it's very expensive. Therefore, we had to make a cut, so the new package repositories have packages starting with Kubernetes versions that were actively supported at the time we introduced the new package repositories.

We recommend looking for alternatives, such as:

- using binaries instead of packages (see "Without a package manager" instructions on this page as an example https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)
- building your own packages, you might be able to find sources for old packages in the git history of this repository

Please see the deprecation blog post for more information: https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

/close
