### ISSUE TITLE
debian packages for v1.28.9 not available

### ISSUE THREAD

**Issue by clementnuss** [kubernetes/release#3623]
#### What happened:

Packages for v1.28.9 are not available. v1.28.8 and v1.28.10 do work

#### What you expected to happen:

Downloading the package for v1.28.9 should work.

#### How to reproduce it (as minimally and precisely as possible):

reach out to https://pkgs.k8s.io/core:/stable:/v1.28/deb/amd64/kubelet_1.28.9-1.1_amd64.deb

<img width="961" alt="image" src="https://github.com/kubernetes/release/assets/2116997/981d2513-d20c-40b9-9114-564cfa3b52c5">

#### Anything else we need to know?:

it works fine for [v1.28.8](https://pkgs.k8s.io/core:/stable:/v1.28/deb/amd64/kubelet_1.28.8-1.1_amd64.deb) or [v1.28.10](https://pkgs.k8s.io/core:/stable:/v1.28/deb/amd64/kubelet_1.28.10-1.1_amd64.deb)

#### Environment:

not relevant.

**Comment by xmudrii** [comment]
Deb packages for patch releases released in April have the suffix `-2.1` instead of `-1.1` because we had to run the build process two times. That said, the valid URL is `https://pkgs.k8s.io/core:/stable:/v1.28/deb/amd64/kubelet_1.28.9-2.1_amd64.deb`.

We strongly recommend not depending on the suffix being `-1.1` all the time because it's automatically generated by the build system.

I'll close this ticket, but if you have any other problem, please let us know and we'll reopen it.
/close
