### ISSUE TITLE
Generated docs checked in on release branch

### ISSUE THREAD

**Issue by enisoc** [kubernetes/release#470]
The release-1.9 branch has generated docs checked in:

https://github.com/kubernetes/kubernetes/blob/release-1.9/docs/admin/cloud-controller-manager.md

This is causing `hack/verify-generated-docs.sh` to fail on the branch.

The release-1.8 branch has only the boilerplate checked in:

https://github.com/kubernetes/kubernetes/blob/release-1.8/docs/admin/cloud-controller-manager.md

Which state is correct? Was this an intentional change in the release tooling between 1.8 and 1.9?

**Comment by enisoc** [comment]
For previous branches, it looks like `verify-generated-docs.sh` passed because we would run `update-generated-docs.sh`, which clobbers the generated docs placed there by anago when first creating the branch:

https://github.com/kubernetes/kubernetes/commits/release-1.8/docs/admin/cloud-controller-manager.md

**Comment by david-mcmahon** [comment]
We've [been here before](https://github.com/kubernetes/kubernetes/issues/44533) and that issue covers the gist of the problem though we never fully sorted it out.

The *-generated-docs.sh scripts are poorly named.  Those generate and verify the stubs only.

`hack/generate-docs.sh` creates real docs on the branches (currently) at branch time (and at branch fast-forward time since `branchff` overwrites the branch with master content).  

I believe the way forward here is to stop trying to juggle stubs and generated docs between branches and just generate at release time.  I had previously not liked this idea, but ultimately I'm finding it's probably the right thing to do.  And it won't require trying to manage *-generated-docs.sh via {update,verify}-all.sh  on master vs. release-* branches.

PR coming...
