### ISSUE TITLE
Release note generation ignores automatic cherrypick release notes

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/release#501]
While releasing 1.9.2 I realized that some of the CPs does not show up in the release notes. It look like release notes on CPs are completely ignored and if the parent PR does not have release note they would not show up in the release note. I would suggest we improve this process by using CP release note or fail on these type of PRs. Difference between release note labels or even release note string probably should fail the release demanding a fix.

**Comment by enisoc** [comment]
I agree we should improve the automation here. FYI section 2 in [the playbook](https://github.com/kubernetes/sig-release/blob/master/release-process-documentation/release-team-guides/patch-release-manager-playbook.md#cherrypick-requests) summarizes the current logic used.

**Comment by david-mcmahon** [comment]
This is WAI from what I remember.  In fact there were lengthy and contentious discussions over how this should work ultimately ending up with the source of truth being the original PR.  That's the history and we're of course welcome to change it.

There was a doc somewhere in k/k that has since been moved that describes this process.  If it is not easily discoverable we should include a link to it and/or mention it somewhere along the cherry pick pipeline including in the output of the cherry-pick script and/or the PR it creates.
