### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by dims** [kubernetes/release#637]
Please see https://reproducible-builds.org/ specifically https://reproducible-builds.org/docs/ on ideas about how to do deterministic builds. When we get a chance, we should try to examine how far away we are from this goal and what our blockers are.

Thanks,
Dims

**Comment by ixdy** [comment]
@bmwiedemann has done some work on this already in https://github.com/kubernetes/kubernetes/issues/48710.

For more increased reproducibility, we should probably be setting `SOURCE_DATE_EPOCH` in release builds (we already do this in CI), though there are still a few other bits missing.

**Comment by bmwiedemann** [comment]
Latest state can be seen in
http://rb.zq1.de/compare.factory/kubernetes-compare.out for openSUSE
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/kubernetes.html

**Comment by dims** [comment]
@bmwiedemann i can't seem to tell if the results are from the latest k8s releases. if not is there a way to trigger these for say the v1.12-rc1 please?

**Comment by bmwiedemann** [comment]
openSUSE's diff is from 1.11.1 (and we do have SOURCE_DATE_EPOCH set)

Going to 1.12 is not that easy, because my reproducibility-test tools are designed around building of packages and there are usually so many changes and build is so slow (~20 minutes per try) that it can take hours to get right.

However, IMHO it would be a good start to find out if and how the two known issues in 1.11.1 have been addressed. If there are patches, I could apply them to 1.11.1 and see if anything remains there.

I'd prefer to not have to chase the master branch.

**Comment by dims** [comment]
gotcha thanks @bmwiedemann

**Comment by dims** [comment]
@bmwiedemann please see https://github.com/kubernetes/kubernetes/pull/68983 to see if it fixes the man page issue

**Comment by bmwiedemann** [comment]
regarding random build-ids:
https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/ seems to imply that it is already possible to generate reproducible go binaries and indeed our openSUSE "docker" package is already reproducible (we always build in the same path)

strace showed me

execve("/usr/lib64/go/1.10/pkg/tool/linux_amd64/compile", ["/usr/lib64/go/1.10/pkg/tool/linux_amd64/compile", "-o", "/tmp/go-build336594203/b073/_pkg_.a", **"-trimpath", "/tmp/go-build336594203/b073",** "-p", "k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets", "-complete", **"-buildid", "SUvgWqVQmIZMGMbPSYtX/SUvgWqVQmIZMGMbPSYtX"**, "-goversion", "go1.10.3", "-D", "", "-importcfg", "/tmp/go-build336594203/b073/importcfg", "-pack", "-c=4", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/byte.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/doc.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/empty.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/int.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/int64.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/string.go"],

so my guess is that a part of the build system generates explicit random buildids instead of using something reproducible (e.g. a constant or the shasum of the source(s))
Maybe `go` would even do the right thing (like gcc) when no buildid is given?

**Comment by dims** [comment]
@bmwiedemann i could get reproducible builds with latest master. PR is here. here's what i had to do.
- `make quick-release` builds stuff inside a docker container, so we control a lot of the things including go version, paths etc.

But that was not enough. then i had to add `trimpath`
- https://github.com/kubernetes/kubernetes/pull/69003/commits/1f74a33790ce5112e4eac622e10be56819058dff#diff-dac3f0d616ae45f98d45d6420ed1be65R671

And then added `-s -w` to remove the symbol table
- https://github.com/kubernetes/kubernetes/pull/69003/commits/1f74a33790ce5112e4eac622e10be56819058dff#diff-dac3f0d616ae45f98d45d6420ed1be65R670

and finally pass the SOURCE_DATE_EPOCH into the container where the builds happen.
- https://github.com/kubernetes/kubernetes/pull/69003/commits/1f74a33790ce5112e4eac622e10be56819058dff#diff-0ee501c7b4b1ab61678579826c6d6534R603

**Comment by dims** [comment]
This issue was moved to kubernetes/kubernetes#70131
