### ISSUE TITLE
bsdmainutils requirement limits gcbmgr to debian distros

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#684]
In pull request #667 
```
commit e7685c51783afc6577bac7cb787c9e5a783c159a
Author: Hannes Hörl <hhorl@pivotal.io>
Date:   Mon Feb 25 09:17:29 2019 +0000

    Make sure essential packages are installed
```
adds "bsdmainutils" package to the gcbmgr package check list.  Lacking this package installed on Fedora, the following is displayed:
```
Checking required system packages: FAILED
PREREQ: Missing prerequisites: bsdmainutils Run the following and try again:

$ sudo dnf install bsdmainutils

Exiting...
```
That does not work as there is no bsdmainutils package in the Fedora ecosystem.

Debian [info](https://packages.debian.org/sid/bsdmainutils) for the package indicates quite a number of utilities:
```
It provides banner (as printerbanner), calendar, col, colcrt, colrm, column, from (as bsd-from), hexdump (or hd), look, lorder, ncal (or cal), ul, and write (as bsd-write).
```
These come from a variety of locations in Fedora.

**Comment by tpepper** [comment]
I'm guessing it was pulled in for 'column', which Fedora gets via util-linux.

**Comment by pswica** [comment]
What would you think of changing common::check_packages to something like:
` 
for prereq in $*; do
  command -v $PREREQ > /dev/null 2>&1 || missing+=($prereq)
done
if ((${#missing[@]}>0)); then
    logecho -r "$FAILED"
   logecho "PREREQ: Missing prerequisites: ${missing[@]}"
  return 1
fi
`
Where the prerequisites are binaries rather than packages. This way, when distributions differ on package management there's no need to update the script. I assume that whoever is using the script can figure out how to install the required bins. 

I'm a bit new to contributing to open source, and this repo, so apologies if I'm making assumptions. Let me know if you think this is good idea and I can try a PR.

**Comment by pswica** [comment]
@hoegaarden 
My PR above should have resolved this. Let me know if it's good to close

**Comment by idealhack** [comment]
/remove-lifecycle stale

since the change of linked PR got reverted later after its merge.
