### ISSUE TITLE
relnotes: add more validation

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#901]
We have a tool which tries to calculate release notes automatically for a patch release and it compares the release branch and master.  It's been shown to be erroneous, eg: https://github.com/kubernetes/release/issues/899
It would be useful to have something that looks for simply "release-note" label in either the release branch or master branch and generates a list of PR numbers which are expected to have a release note for visual or programmatic comparison against the list of PR numbers for which the generator actually captured release note text.

Also we have people putting slightly different things for a "none" indication in the release notes block in the PR description, eg:

 * https://github.com/kubernetes/kubernetes/pull/80563/files#diff-7ce0da8ad6adf39c0d46fc012603d6aaL126
 * https://github.com/kubernetes/kubernetes/pull/80563/files#diff-7ce0da8ad6adf39c0d46fc012603d6aaL130
 * https://github.com/kubernetes/kubernetes/pull/80563/files#diff-7ce0da8ad6adf39c0d46fc012603d6aaL200

This feels like something we could test for with a regex list and highlight for fixing in the PR.

**Comment by saschagrunert** [comment]
I think we should consider adding something like end-to-end tests to the release notes tooling. We could create expectation snapshots for different test cases and run the tests continuously in prow.

**Comment by saschagrunert** [comment]
@tpepper @justaugustus I think we can close this issue, because it will be solved from my point of view when we're start using `krel changelog` for patch releases.

We already backtrack cherry-picks in the golang based tool:
https://github.com/kubernetes/release/blob/99f19f5818dce55903df1e9aec3fbe82226b5884/pkg/notes/notes.go#L768-L795

This means that the release note on a cherry-pick has the highest priority, while falling back to the note of the origin PR if the cherry-pick has none. We can verify this in our existing integration test with recorded GitHub API:

We're validating this release notes entry:
https://github.com/kubernetes/release/blob/99f19f5818dce55903df1e9aec3fbe82226b5884/cmd/krel/cmd/changelog_data_test.go#L33

We can see that the [cherry-pick PR](https://github.com/kubernetes/kubernetes/pull/83776) contains the note wheres the [original PR](https://github.com/kubernetes/kubernetes/pull/83609) not.

**Comment by saschagrunert** [comment]
I think chis can be closed because we do not rely on the old scripts any more and the mentioned issues seem to be fixed.

/close
